version: '3.9'

services:
   mysqldb:
     image: mysql:5.7
     environment:
      MYSQL_DATABASE_FILE: /run/secrets/db_name
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
     networks:
      - webnet
     volumes:
       - db:/var/lib/mysql
     secrets:
       - db_password
       - db_user
       - db_name


   adminer:
     image: adminer:latest
     ports:
       - "8080:8080"
     networks:
       - webnet


   wordpress:
     image: wordpress:latest
     deploy:
       replicas: 3
       update_config:
          parallelism: 2
          delay: 10s
          order: stop-first
     depends_on:
       - mysqldb
     ports:
       - "8000:80"
     networks:
       - webnet
     environment:
       WORDPRESS_DB_HOST: mysqldb
       WORDPRESS_DB_USER_FILE: /run/secrets/db_user
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
       WORDPRESS_DB_NAME_FILE: /run/secrets/db_name
     volumes:
       - wordpress:/var/www/html
     secrets:
       - db_password
       - db_user
       - db_name

networks:
  webnet:
    driver: overlay
volumes:
  wordpress: {}
  db: {}
secrets:
  db_password:
    file: ./db_password.txt
  db_user:
    file: ./db_user.txt
  db_name:
    file: ./db_name.txt

